{{- if .Values.app.enabled }}
{{- $externalURL := include "kite.externalURL" . -}}
apiVersion: app.sealos.io/v1
kind: App
metadata:
  name: kite
  namespace: app-system
spec:
  type: iframe
  name: kite
  displayType: normal
  icon: {{ printf "%s/logo.svg" $externalURL | quote }}
  data:
    desc: "Kite Dashboard"
    url: {{ $externalURL | quote }}
  i18n:
    zh:
      name: Kite
    zh-Hans:
      name: Kite
{{- end }}
