{{- if .Values.ingress.enabled -}}
{{- $host := include "kite.externalHost" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kite.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kite.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'
spec:
  ingressClassName: nginx
  {{- if eq (include "kite.ingressTlsEnabled" .) "true" }}
  tls:
    - hosts:
        - {{ $host | quote }}
      secretName: {{ .Values.certSecretName | quote }}
  {{- end }}
  rules:
    - host: {{ $host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "kite.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
{{- end }}
