type: sqlite

postgres:
  native:
    enabled: true
    clusterName: ""
    credentialSecretName: ""
    version: postgresql-14.8.0
    replicas: 2
    storage: 3Gi
    backup:
      enabled: true
      cron: "0 7 * * *"
      retentionPeriod: 7d
    resources:
      limits:
        cpu: 1000m
        memory: 1024Mi
      requests:
        cpu: 10m
        memory: 50Mi
    terminationPolicy: Delete
